/**
 * Language file generator: en_us (English) only.
 * <p>Convention: for each newly registered item/block, append one addXxx line in
 * {@link com.zeqhyrsquall.uraniumcontaminationeraii.datagen.lang.ModEnglishLangProvider} —
 * JSON is generated by DataGen; hand-writing lang files is forbidden.</p>
 */
package com.zeqhyrsquall.uraniumcontaminationeraii.datagen.lang;
